import type { FeatureDictionary } from "@/i18n/feature";

export type BillingStrings = {
  pricingTitle: string;
  pricingSubtitle: string;
  monthly: string;
  annual: string;
  annualHint: string;
  perMonth: string;
  perYear: string;
  currentPlan: string;
  choosePlan: string;
  upgrade: string;
  downgrade: string;
  renew: string;
  free: string;
  mostPopular: string;
  testMode: string;
  signInToSubscribe: string;
  billingTitle: string;
  billingSubtitle: string;
  plan: string;
  status: string;
  renewsOn: string;
  endsOn: string;
  interval: string;
  cancel: string;
  cancelConfirm: string;
  resume: string;
  canceledNotice: string;
  graceNotice: string;
  changePlan: string;
  invoices: string;
  invoiceNumber: string;
  amount: string;
  date: string;
  noInvoices: string;
  history: string;
  noHistory: string;
  statuses: Record<string, string>;
  events: Record<string, string>;
  premiumOnly: string;
  premiumOnlyText: string;
  seePlans: string;
  error: string;
  processing: string;
};

export const billingStrings: FeatureDictionary<BillingStrings> = {
  ar: {
    pricingTitle: "باقات العضوية",
    pricingSubtitle: "اختر الباقة التي تناسب رحلتك نحو الزواج",
    monthly: "شهري",
    annual: "سنوي",
    annualHint: "وفّر شهرين",
    perMonth: "/ شهريًا",
    perYear: "/ سنويًا",
    currentPlan: "باقتك الحالية",
    choosePlan: "اختر هذه الباقة",
    upgrade: "ترقية",
    downgrade: "تخفيض الباقة",
    renew: "تجديد الآن",
    free: "مجانًا",
    mostPopular: "الأكثر اختيارًا",
    testMode: "وضع تجريبي: لا يتم خصم أي مبلغ حاليًا.",
    signInToSubscribe: "سجّل الدخول للاشتراك",
    billingTitle: "الاشتراك والفواتير",
    billingSubtitle: "إدارة باقتك وسجل مدفوعاتك",
    plan: "الباقة",
    status: "الحالة",
    renewsOn: "يتجدد في",
    endsOn: "ينتهي في",
    interval: "دورة الفوترة",
    cancel: "إلغاء الاشتراك",
    cancelConfirm: "سيبقى اشتراكك فعّالًا حتى نهاية الفترة الحالية. هل تريد المتابعة؟",
    resume: "استئناف الاشتراك",
    canceledNotice: "تم إلغاء التجديد التلقائي — تبقى مزاياك حتى نهاية الفترة.",
    graceNotice: "تعذّر تحصيل الدفعة. لديك فترة سماح قبل إيقاف المزايا.",
    changePlan: "تغيير الباقة",
    invoices: "الفواتير",
    invoiceNumber: "رقم الفاتورة",
    amount: "المبلغ",
    date: "التاريخ",
    noInvoices: "لا توجد فواتير بعد.",
    history: "سجل الاشتراك",
    noHistory: "لا يوجد نشاط بعد.",
    statuses: {
      trialing: "فترة تجريبية",
      active: "نشط",
      past_due: "متأخر السداد",
      canceled: "ملغى",
      expired: "منتهٍ",
      succeeded: "مدفوعة",
      failed: "فاشلة",
      pending: "قيد المعالجة",
      refunded: "مستردة",
    },
    events: {
      checkout: "بدء الاشتراك",
      activated: "تفعيل الباقة",
      upgraded: "ترقية الباقة",
      downgraded: "تخفيض الباقة",
      canceled: "إلغاء التجديد",
      resumed: "استئناف الاشتراك",
      renewed: "تجديد",
      payment_succeeded: "دفعة ناجحة",
      payment_failed: "دفعة فاشلة",
      grace_started: "بدء فترة السماح",
      expired: "انتهاء الاشتراك",
      refunded: "استرداد",
    },
    premiumOnly: "ميزة بريميوم",
    premiumOnlyText: "قم بالترقية للاستفادة من هذه الميزة.",
    seePlans: "عرض الباقات",
    error: "تعذّر إتمام العملية. حاول مرة أخرى.",
    processing: "جارٍ المعالجة…",
  },
  en: {
    pricingTitle: "Membership plans",
    pricingSubtitle: "Pick the plan that fits your journey to marriage",
    monthly: "Monthly",
    annual: "Annual",
    annualHint: "2 months free",
    perMonth: "/ month",
    perYear: "/ year",
    currentPlan: "Your current plan",
    choosePlan: "Choose this plan",
    upgrade: "Upgrade",
    downgrade: "Switch down",
    renew: "Renew now",
    free: "Free",
    mostPopular: "Most popular",
    testMode: "Test mode: no money is charged yet.",
    signInToSubscribe: "Sign in to subscribe",
    billingTitle: "Subscription & invoices",
    billingSubtitle: "Manage your plan and payment history",
    plan: "Plan",
    status: "Status",
    renewsOn: "Renews on",
    endsOn: "Ends on",
    interval: "Billing cycle",
    cancel: "Cancel subscription",
    cancelConfirm: "Your plan stays active until the end of the current period. Continue?",
    resume: "Resume subscription",
    canceledNotice: "Auto-renew is off — your benefits last until the period ends.",
    graceNotice: "We couldn't collect your payment. You're in a grace period.",
    changePlan: "Change plan",
    invoices: "Invoices",
    invoiceNumber: "Invoice",
    amount: "Amount",
    date: "Date",
    noInvoices: "No invoices yet.",
    history: "Subscription history",
    noHistory: "No activity yet.",
    statuses: {
      trialing: "Trial",
      active: "Active",
      past_due: "Past due",
      canceled: "Canceled",
      expired: "Expired",
      succeeded: "Paid",
      failed: "Failed",
      pending: "Pending",
      refunded: "Refunded",
    },
    events: {
      checkout: "Checkout started",
      activated: "Plan activated",
      upgraded: "Upgraded",
      downgraded: "Downgraded",
      canceled: "Auto-renew canceled",
      resumed: "Subscription resumed",
      renewed: "Renewed",
      payment_succeeded: "Payment succeeded",
      payment_failed: "Payment failed",
      grace_started: "Grace period started",
      expired: "Subscription expired",
      refunded: "Refunded",
    },
    premiumOnly: "Premium feature",
    premiumOnlyText: "Upgrade your plan to unlock this.",
    seePlans: "See plans",
    error: "Something went wrong. Please try again.",
    processing: "Processing…",
  },
  de: {
    pricingTitle: "Mitgliedschaften",
    pricingSubtitle: "Wähle den Plan, der zu deiner Suche passt",
    monthly: "Monatlich",
    annual: "Jährlich",
    annualHint: "2 Monate gratis",
    perMonth: "/ Monat",
    perYear: "/ Jahr",
    currentPlan: "Dein aktueller Plan",
    choosePlan: "Diesen Plan wählen",
    upgrade: "Upgrade",
    downgrade: "Herabstufen",
    renew: "Jetzt verlängern",
    free: "Kostenlos",
    mostPopular: "Am beliebtesten",
    testMode: "Testmodus: Es wird noch nichts abgebucht.",
    signInToSubscribe: "Zum Abonnieren anmelden",
    billingTitle: "Abo & Rechnungen",
    billingSubtitle: "Plan und Zahlungsverlauf verwalten",
    plan: "Plan",
    status: "Status",
    renewsOn: "Verlängert am",
    endsOn: "Endet am",
    interval: "Abrechnungszeitraum",
    cancel: "Abo kündigen",
    cancelConfirm: "Dein Plan bleibt bis zum Periodenende aktiv. Fortfahren?",
    resume: "Abo fortsetzen",
    canceledNotice: "Automatische Verlängerung ist aus — Vorteile bleiben bis Periodenende.",
    graceNotice: "Zahlung fehlgeschlagen. Du bist in der Kulanzfrist.",
    changePlan: "Plan wechseln",
    invoices: "Rechnungen",
    invoiceNumber: "Rechnung",
    amount: "Betrag",
    date: "Datum",
    noInvoices: "Noch keine Rechnungen.",
    history: "Abo-Verlauf",
    noHistory: "Noch keine Aktivität.",
    statuses: {
      trialing: "Testphase",
      active: "Aktiv",
      past_due: "Überfällig",
      canceled: "Gekündigt",
      expired: "Abgelaufen",
      succeeded: "Bezahlt",
      failed: "Fehlgeschlagen",
      pending: "Ausstehend",
      refunded: "Erstattet",
    },
    events: {
      checkout: "Checkout gestartet",
      activated: "Plan aktiviert",
      upgraded: "Upgrade",
      downgraded: "Herabgestuft",
      canceled: "Verlängerung gekündigt",
      resumed: "Abo fortgesetzt",
      renewed: "Verlängert",
      payment_succeeded: "Zahlung erfolgreich",
      payment_failed: "Zahlung fehlgeschlagen",
      grace_started: "Kulanzfrist gestartet",
      expired: "Abo abgelaufen",
      refunded: "Erstattet",
    },
    premiumOnly: "Premium-Funktion",
    premiumOnlyText: "Upgrade, um das freizuschalten.",
    seePlans: "Pläne ansehen",
    error: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    processing: "Wird verarbeitet…",
  },
  fr: {
    pricingTitle: "Tarifs",
    pricingSubtitle: "Choisissez la formule adaptée à votre parcours vers le mariage",
    monthly: "Mensuel",
    annual: "Annuel",
    annualHint: "2 mois offerts",
    perMonth: "/ mois",
    perYear: "/ an",
    currentPlan: "Votre formule actuelle",
    choosePlan: "Choisir cette formule",
    upgrade: "Passer à supérieur",
    downgrade: "Rétrograder",
    renew: "Renouveler",
    free: "Gratuit",
    mostPopular: "Le plus populaire",
    testMode: "Mode test : aucun prélèvement réel.",
    signInToSubscribe: "Connectez-vous pour vous abonner",
    billingTitle: "Abonnement et factures",
    billingSubtitle: "Gérez votre formule et l'historique des paiements",
    plan: "Formule",
    status: "Statut",
    renewsOn: "Renouvellement",
    endsOn: "Fin",
    interval: "Période de facturation",
    cancel: "Annuler l'abonnement",
    cancelConfirm: "Votre formule restera active jusqu'à la fin de la période. Continuer ?",
    resume: "Reprendre l'abonnement",
    canceledNotice: "Renouvellement automatique désactivé — accès jusqu'à la fin de la période.",
    graceNotice: "Le paiement a échoué. Une période de grâce est en cours.",
    changePlan: "Changer de formule",
    invoices: "Factures",
    invoiceNumber: "Facture",
    amount: "Montant",
    date: "Date",
    noInvoices: "Aucune facture pour l'instant.",
    history: "Historique de l'abonnement",
    noHistory: "Aucune activité pour l'instant.",
    statuses: {
      trialing: "Essai",
      active: "Actif",
      past_due: "En retard",
      canceled: "Annulé",
      expired: "Expiré",
      succeeded: "Payé",
      failed: "Échec",
      pending: "En cours",
      refunded: "Remboursé",
    },
    events: {
      checkout: "Paiement démarré",
      activated: "Formule activée",
      upgraded: "Montée en gamme",
      downgraded: "Passage à une formule inférieure",
      canceled: "Renouvellement automatique annulé",
      resumed: "Abonnement repris",
      renewed: "Renouvellement",
      payment_succeeded: "Paiement réussi",
      payment_failed: "Paiement échoué",
      grace_started: "Période de grâce",
      expired: "Abonnement expiré",
      refunded: "Remboursement",
    },
    premiumOnly: "Fonctionnalité Premium",
    premiumOnlyText: "Améliorez votre formule pour y accéder.",
    seePlans: "Voir les tarifs",
    error: "Une erreur est survenue. Veuillez réessayer.",
    processing: "Traitement…",
  },
};