import type { FeatureDictionary } from "@/i18n/feature";

export type BillingStrings = {
  pricingTitle: string;
  pricingSubtitle: string;
  monthly: string;
  annual: string;
  annualHint: string;
  perMonth: string;
  perYear: string;
  currentPlan: string;
  choosePlan: string;
  upgrade: string;
  downgrade: string;
  renew: string;
  free: string;
  mostPopular: string;
  testMode: string;
  signInToSubscribe: string;
  billingTitle: string;
  billingSubtitle: string;
  plan: string;
  status: string;
  renewsOn: string;
  endsOn: string;
  interval: string;
  cancel: string;
  cancelConfirm: string;
  resume: string;
  canceledNotice: string;
  graceNotice: string;
  changePlan: string;
  invoices: string;
  invoiceNumber: string;
  amount: string;
  date: string;
  noInvoices: string;
  history: string;
  noHistory: string;
  statuses: Record<string, string>;
  events: Record<string, string>;
  premiumOnly: string;
  premiumOnlyText: string;
  seePlans: string;
  error: string;
  processing: string;
};

export const billingStrings: FeatureDictionary<BillingStrings> = {
  ar: {
    pricingTitle: "باقات العضوية",
    pricingSubtitle: "اختر الباقة التي تناسب رحلتك نحو الزواج",
    monthly: "شهري",
    annual: "سنوي",
    annualHint: "وفّر شهرين",
    perMonth: "/ شهريًا",
    perYear: "/ سنويًا",
    currentPlan: "باقتك الحالية",
    choosePlan: "اختر هذه الباقة",
    upgrade: "ترقية",
    downgrade: "تخفيض الباقة",
    renew: "تجديد الآن",
    free: "مجانًا",
    mostPopular: "الأكثر اختيارًا",
    testMode: "وضع تجريبي: لا يتم خصم أي مبلغ حاليًا.",
    signInToSubscribe: "سجّل الدخول للاشتراك",
    billingTitle: "الاشتراك والفواتير",
    billingSubtitle: "إدارة باقتك وسجل مدفوعاتك",
    plan: "الباقة",
    status: "الحالة",
    renewsOn: "يتجدد في",
    endsOn: "ينتهي في",
    interval: "دورة الفوترة",
    cancel: "إلغاء الاشتراك",
    cancelConfirm: "سيبقى اشتراكك فعّالًا حتى نهاية الفترة الحالية. هل تريد المتابعة؟",
    resume: "استئناف الاشتراك",
    canceledNotice: "تم إلغاء التجديد التلقائي — تبقى مزاياك حتى نهاية الفترة.",
    graceNotice: "تعذّر تحصيل الدفعة. لديك فترة سماح قبل إيقاف المزايا.",
    changePlan: "تغيير الباقة",
    invoices: "الفواتير",
    invoiceNumber: "رقم الفاتورة",
    amount: "المبلغ",
    date: "التاريخ",
    noInvoices: "لا توجد فواتير بعد.",
    history: "سجل الاشتراك",
    noHistory: "لا يوجد نشاط بعد.",
    statuses: {
      trialing: "فترة تجريبية",
      active: "نشط",
      past_due: "متأخر السداد",
      canceled: "ملغى",
      expired: "منتهٍ",
      succeeded: "مدفوعة",
      failed: "فاشلة",
      pending: "قيد المعالجة",
      refunded: "مستردة",
    },
    events: {
      checkout: "بدء الاشتراك",
      activated: "تفعيل الباقة",
      upgraded: "ترقية الباقة",
      downgraded: "تخفيض الباقة",
      canceled: "إلغاء التجديد",
      resumed: "استئناف الاشتراك",
      renewed: "تجديد",
      payment_succeeded: "دفعة ناجحة",
      payment_failed: "دفعة فاشلة",
      grace_started: "بدء فترة السماح",
      expired: "انتهاء الاشتراك",
      refunded: "استرداد",
    },
    premiumOnly: "ميزة بريميوم",
    premiumOnlyText: "قم بالترقية للاستفادة من هذه الميزة.",
    seePlans: "عرض الباقات",
    error: "تعذّر إتمام العملية. حاول مرة أخرى.",
    processing: "جارٍ المعالجة…",
  },
  en: {
    pricingTitle: "Membership plans",
    pricingSubtitle: "Pick the plan that fits your journey to marriage",
    monthly: "Monthly",
    annual: "Annual",
    annualHint: "2 months free",
    perMonth: "/ month",
    perYear: "/ year",
    currentPlan: "Your current plan",
    choosePlan: "Choose this plan",
    upgrade: "Upgrade",
    downgrade: "Switch down",
    renew: "Renew now",
    free: "Free",
    mostPopular: "Most popular",
    testMode: "Test mode: no money is charged yet.",
    signInToSubscribe: "Sign in to subscribe",
    billingTitle: "Subscription & invoices",
    billingSubtitle: "Manage your plan and payment history",
    plan: "Plan",
    status: "Status",
    renewsOn: "Renews on",
    endsOn: "Ends on",
    interval: "Billing cycle",
    cancel: "Cancel subscription",
    cancelConfirm: "Your plan stays active until the end of the current period. Continue?",
    resume: "Resume subscription",
    canceledNotice: "Auto-renew is off — your benefits last until the period ends.",
    graceNotice: "We couldn't collect your payment. You're in a grace period.",
    changePlan: "Change plan",
    invoices: "Invoices",
    invoiceNumber: "Invoice",
    amount: "Amount",
    date: "Date",
    noInvoices: "No invoices yet.",
    history: "Subscription history",
    noHistory: "No activity yet.",
    statuses: {
      trialing: "Trial",
      active: "Active",
      past_due: "Past due",
      canceled: "Canceled",
      expired: "Expired",
      succeeded: "Paid",
      failed: "Failed",
      pending: "Pending",
      refunded: "Refunded",
    },
    events: {
      checkout: "Checkout started",
      activated: "Plan activated",
      upgraded: "Upgraded",
      downgraded: "Downgraded",
      canceled: "Auto-renew canceled",
      resumed: "Subscription resumed",
      renewed: "Renewed",
      payment_succeeded: "Payment succeeded",
      payment_failed: "Payment failed",
      grace_started: "Grace period started",
      expired: "Subscription expired",
      refunded: "Refunded",
    },
    premiumOnly: "Premium feature",
    premiumOnlyText: "Upgrade your plan to unlock this.",
    seePlans: "See plans",
    error: "Something went wrong. Please try again.",
    processing: "Processing…",
  },
  de: {
    pricingTitle: "Mitgliedschaften",
    pricingSubtitle: "Wähle den Plan, der zu deiner Suche passt",
    monthly: "Monatlich",
    annual: "Jährlich",
    annualHint: "2 Monate gratis",
    perMonth: "/ Monat",
    perYear: "/ Jahr",
    currentPlan: "Dein aktueller Plan",
    choosePlan: "Diesen Plan wählen",
    upgrade: "Upgrade",
    downgrade: "Herabstufen",
    renew: "Jetzt verlängern",
    free: "Kostenlos",
    mostPopular: "Am beliebtesten",
    testMode: "Testmodus: Es wird noch nichts abgebucht.",
    signInToSubscribe: "Zum Abonnieren anmelden",
    billingTitle: "Abo & Rechnungen",
    billingSubtitle: "Plan und Zahlungsverlauf verwalten",
    plan: "Plan",
    status: "Status",
    renewsOn: "Verlängert am",
    endsOn: "Endet am",
    interval: "Abrechnungszeitraum",
    cancel: "Abo kündigen",
    cancelConfirm: "Dein Plan bleibt bis zum Periodenende aktiv. Fortfahren?",
    resume: "Abo fortsetzen",
    canceledNotice: "Automatische Verlängerung ist aus — Vorteile bleiben bis Periodenende.",
    graceNotice: "Zahlung fehlgeschlagen. Du bist in der Kulanzfrist.",
    changePlan: "Plan wechseln",
    invoices: "Rechnungen",
    invoiceNumber: "Rechnung",
    amount: "Betrag",
    date: "Datum",
    noInvoices: "Noch keine Rechnungen.",
    history: "Abo-Verlauf",
    noHistory: "Noch keine Aktivität.",
    statuses: {
      trialing: "Testphase",
      active: "Aktiv",
      past_due: "Überfällig",
      canceled: "Gekündigt",
      expired: "Abgelaufen",
      succeeded: "Bezahlt",
      failed: "Fehlgeschlagen",
      pending: "Ausstehend",
      refunded: "Erstattet",
    },
    events: {
      checkout: "Checkout gestartet",
      activated: "Plan aktiviert",
      upgraded: "Upgrade",
      downgraded: "Herabgestuft",
      canceled: "Verlängerung gekündigt",
      resumed: "Abo fortgesetzt",
      renewed: "Verlängert",
      payment_succeeded: "Zahlung erfolgreich",
      payment_failed: "Zahlung fehlgeschlagen",
      grace_started: "Kulanzfrist gestartet",
      expired: "Abo abgelaufen",
      refunded: "Erstattet",
    },
    premiumOnly: "Premium-Funktion",
    premiumOnlyText: "Upgrade, um das freizuschalten.",
    seePlans: "Pläne ansehen",
    error: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    processing: "Wird verarbeitet…",
  },
  ru: {
    pricingTitle: "Тарифы",
    pricingSubtitle: "Выберите план для вашего пути к браку",
    monthly: "Ежемесячно",
    annual: "Ежегодно",
    annualHint: "2 месяца бесплатно",
    perMonth: "/ месяц",
    perYear: "/ год",
    currentPlan: "Ваш текущий план",
    choosePlan: "Выбрать план",
    upgrade: "Улучшить",
    downgrade: "Понизить",
    renew: "Продлить",
    free: "Бесплатно",
    mostPopular: "Популярный",
    testMode: "Тестовый режим: списаний нет.",
    signInToSubscribe: "Войдите, чтобы оформить",
    billingTitle: "Подписка и счета",
    billingSubtitle: "Управление планом и историей платежей",
    plan: "План",
    status: "Статус",
    renewsOn: "Продление",
    endsOn: "Заканчивается",
    interval: "Период оплаты",
    cancel: "Отменить подписку",
    cancelConfirm: "План будет активен до конца периода. Продолжить?",
    resume: "Возобновить подписку",
    canceledNotice: "Автопродление выключено — доступ до конца периода.",
    graceNotice: "Платёж не прошёл. Действует льготный период.",
    changePlan: "Сменить план",
    invoices: "Счета",
    invoiceNumber: "Счёт",
    amount: "Сумма",
    date: "Дата",
    noInvoices: "Счетов пока нет.",
    history: "История подписки",
    noHistory: "Активности пока нет.",
    statuses: {
      trialing: "Пробный",
      active: "Активен",
      past_due: "Просрочен",
      canceled: "Отменён",
      expired: "Истёк",
      succeeded: "Оплачен",
      failed: "Ошибка",
      pending: "В обработке",
      refunded: "Возврат",
    },
    events: {
      checkout: "Начало оформления",
      activated: "План активирован",
      upgraded: "Улучшение",
      downgraded: "Понижение",
      canceled: "Автопродление отменено",
      resumed: "Подписка возобновлена",
      renewed: "Продление",
      payment_succeeded: "Платёж успешен",
      payment_failed: "Платёж не прошёл",
      grace_started: "Льготный период",
      expired: "Подписка истекла",
      refunded: "Возврат",
    },
    premiumOnly: "Премиум-функция",
    premiumOnlyText: "Улучшите план, чтобы открыть это.",
    seePlans: "Смотреть тарифы",
    error: "Что-то пошло не так. Повторите попытку.",
    processing: "Обработка…",
  },
};